foody/urls.py
from django.urls import path
from . import views


app_name = 'booking'


urlpatterns = [
    path('', views.home, name='home'),
    path('menu', views.meal_list, name='meal_list'),
    path('menu/<slug:slug>', views.meal_detail, name='meal_detail'),
    path('reservation', views.reserve_table, name='reserve_table'),
    path('about-us', views.about_us, name='about_us'),
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('foody.urls', namespace='foody')),
    path('summernote/', include('django_summernote.urls')),
]

foody/models.py
from django.db import models
from django.utils.text import slugify
from datetime import datetime


# Meal List


class Meals(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    category = models.ForeignKey(
        'Category', on_delete=models.SET_NULL, null=True)
    people = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    preparation_time = models.IntegerField()
    image = models.ImageField(upload_to='img/')
    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Meals, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Meal'
        verbose_name_plural = 'Meals'

    def __str__(self):
        return self.name


# Meal Category


class Category(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


# Meal Detail


def meal_detail(request, slug):
    meal_detail = Meals.objects.get(slug=slug)

    context = {'meal_detail': meal_detail, }

    return render(request, 'detail.html', context)


# Reservation Form


class Reservation(models.Model):
    people_choices = (
        ('one', '1 Person'),
        ('two', '2 People'),
        ('three', '3 People'),
        ('four', '4 People'),
        ('five_plus', '5+ People'),
    )

    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length=12)
    number_of_people = models.CharField(
        max_length=10, choices=people_choices, default='one')
    Date = models.DateField(default=datetime.today)
    time = models.TimeField(default=datetime.now)

    def __str__(self):
        return self.name


# Dining Times


class DiningTimes(models.Model):
    name = models.CharField(max_length=30)
    breakfast = models.TextField()
    breakfast_weekend = models.TextField(null=True, blank=True)
    lunch = models.TextField()
    lunch_weekend = models.TextField(null=True, blank=True)
    dinner = models.TextField()
    dinner_weekend = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Dining Times'
        verbose_name_plural = 'Dining Times'

    def __str__(self):
        return self.name

# About Us


class AboutUs(models.Model):
    title = models.CharField(max_length=50)
    section_title = models.CharField(max_length=30)
    content = models.TextField()
    number_a = models.IntegerField()
    title_a_small = models.CharField(max_length=30)
    title_a_big = models.CharField(max_length=30)
    number_b = models.IntegerField()
    title_b_small = models.CharField(max_length=30)
    title_b_big = models.CharField(max_length=30)
    image_left_up = models.ImageField(upload_to='img/aboutus/')
    image_left_down = models.ImageField(upload_to='img/aboutus/')
    image_right_up = models.ImageField(upload_to='img/aboutus/')
    image_right_down = models.ImageField(upload_to='img/aboutus/')

    class Meta:
        verbose_name = 'About Us'
        verbose_name_plural = 'About Us'

    def __str__(self):
        return self.title


class TeamMembers(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=30)
    image = models.ImageField(upload_to='img/team/')
    facebook = models.TextField()
    twitter = models.TextField()
    instagram = models.TextField()

    class Meta:
        verbose_name = 'Team Members'
        verbose_name_plural = 'Team Members'

    def __str__(self):
        return self.name


# Service Cards


class ServiceCards(models.Model):
    title = models.CharField(max_length=50)
    icon = models.TextField()
    content = models.TextField()

    class Meta:
        verbose_name = 'Service Cards'
        verbose_name_plural = 'Service Cards'

    def __str__(self):
        return self.title


# Hero


class HeroContainer(models.Model):
    name = models.CharField(max_length=200, null=True)
    title = models.TextField()
    content = models.TextField()
    image = models.ImageField(upload_to='img/hero/')
    cta_text = models.TextField()

    class Meta:
        verbose_name = 'Hero Container'
        verbose_name_plural = 'Hero Container'

    def __str__(self):
        return self.name


# Testimonials


class Testimonials(models.Model):
    name = models.CharField(max_length=30)
    content = models.TextField()
    image = models.ImageField(upload_to='img/testimonials/')

    class Meta:
        verbose_name = 'Testimonials'
        verbose_name_plural = 'Testimonials'

    def __str__(self):
        return self.name

foody/forms.py
from django import forms
from .models import Reservation


class ReserveTableForm(forms.ModelForm):
    
    class Meta:
        model = Reservation
        fields = '__all__'

foody/views.py
from django.shortcuts import render
from .models import Meals, Category, Reservation, AboutUs, TeamMembers
from .models import ServiceCards, HeroContainer, Testimonials, DiningTimes
from .forms import ReserveTableForm
from django.contrib import messages

# Menu List


def meal_list(request):
    meal_list = Meals.objects.all()
    categories = Category.objects.all()

    context = {
        'meal_list': meal_list,
        'categories': categories,
    }

    return render(request, 'list.html', context)

# Meal Detail


def meal_detail(request, slug):
    meal_detail = Meals.objects.get(slug=slug)

    context = {'meal_detail': meal_detail, }

    return render(request, 'detail.html', context)

# Home Page


def home(request):
    about = AboutUs.objects.last()
    cards = ServiceCards.objects.all()
    hero = HeroContainer.objects.last()
    testimonials = Testimonials.objects.all()

    context = {
        'about': about,
        'cards': cards,
        'hero': hero,
        'testimonials': testimonials,
    }

    return render(request, 'home.html', context)

# About Page


def about_us(request):
    about = AboutUs.objects.last()
    team = TeamMembers.objects.all()

    context = {
        'about': about,
        'team': team,
    }

    return render(request, 'about.html', context)

# Reservation Form


def reserve_table(request):
    timings = DiningTimes.objects.last()
    reserve_form = ReserveTableForm()

    if request.method == 'POST':
        reserve_form = ReserveTableForm(request.POST)

        if reserve_form.is_valid():
            reserve_form.save()
            messages.success(request, "We will contact you for confirmation!")

    context = {
        'form': reserve_form,
        'timings': timings,
    }

    return render(request, 'reservation.html', context)

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- About Start -->
<div class="py-5 bg-custom hero-header mb-5">
    <div class="container text-center my-5 pt-5">
        <h1 class="display-3 text-white mb-3 animated slideInDown">About Us</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-center text-uppercase">
                <li class="breadcrumb-item"><a href="{% url 'foody:home' %}">Home</a></li>
                <li class="breadcrumb-item text-white active" aria-current="page">About Us</li>
            </ol>
        </nav>
    </div>
</div>
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5 align-items-center">
            <div class="col-lg-6">
                <div class="row g-3">
                    <div class="col-6 text-start">
                        <img class="img-fluid rounded w-100  wow fadeInUp"
                            src="{{about.image_left_up.url}}">
                    </div>
                    <div class="col-6 text-start">
                        <img class="img-fluid rounded w-75 wow fadeInUp"
                            src="{{about.image_right_up.url}}" style="margin-top: 25%;">
                    </div>
                    <div class="col-6 text-end">
                        <img class="img-fluid rounded w-75 wow fadeInUp"
                            src="{{about.image_left_down.url}}">
                    </div>
                    <div class="col-6 text-end">
                        <img class="img-fluid rounded w-100 wow fadeInUp"
                            src="{{about.image_right_down.url}}">
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <h5 class="section-title ff-secondary text-start text-h fw-normal">{{about.section_title}}</h5>
                <h1 class="mb-4">{{about.title}}</h1>
                <p class="mb-4">{{about.content | safe}}</p>
                <div class="row g-4 mb-4">
                    <div class="col-sm-6">
                        <div class="d-flex align-items-center border-start border-5 border-primary px-3">
                            <h1 class="flex-shrink-0 display-5 text-h mb-0" data-toggle="counter-up">{{about.number_a}}
                            </h1>
                            <div class="ps-4">
                                <p class="mb-0">{{about.title_a_small}}</p>
                                <h6 class="text-uppercase mb-0">{{about.title_a_big}}</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="d-flex align-items-center border-start border-5 border-primary px-3">
                            <h1 class="flex-shrink-0 display-5 text-h mb-0" data-toggle="counter-up">{{about.number_b}}
                            </h1>
                            <div class="ps-4">
                                <p class="mb-0">{{about.title_b_small}}</p>
                                <h6 class="text-uppercase mb-0">{{about.title_b_big}}</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About End -->

<!-- Team Start -->
<div class="container-xxl pt-5 pb-3">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h5 class="section-title ff-secondary text-center text-h fw-normal">Team Members</h5>
            <h1 class="mb-5">Meet Our Master Chefs</h1>
        </div>
        <div class="row g-4">

            {% for member in team %}

            <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                <div class="team-item text-center rounded overflow-hidden">
                    <div class="rounded-circle overflow-hidden m-4">
                        <img class="img-fluid" src="{{member.image.url}}" alt="Image of the Chef">
                    </div>
                    <h5 class="mb-0">{{member.name}}</h5>
                    <small>{{member.title}}</small>
                    <div class="d-flex justify-content-center mt-3">
                        <a class="btn btn-square btn-primary mx-1" href="{{member.facebook}}" target="_blank"><i
                                class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-square btn-primary mx-1" href="{{member.twitter}}" target="_blank"><i
                                class="fab fa-twitter"></i></a>
                        <a class="btn btn-square btn-primary mx-1" href="{{member.instagram}}" target="_blank"><i
                                class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>

            {% endfor %}

        </div>
    </div>
</div>
<!-- Team End -->

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Foody - The Best Food In Town</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="bg-body-custom p-0">
        <!-- Spinner Start -->
        <div id="spinner"
            class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-h" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Navbar & Hero Start -->
        <div class="position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-dark bg-custom px-4 px-lg-5 py-3 py-lg-0">
                <a href="{% url 'foody:home' %}" class="navbar-brand p-0">
                    <h1 class="text-h m-0"><i class="fa fa-hamburger me-3"></i>Foody</h1>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto py-0 pe-4">
                        <a href="{% url 'foody:home' %}" class="nav-item nav-link">Home</a>
                        <a href="{% url 'foody:about_us' %}" class="nav-item nav-link">About
                            Us</a>
                        <a href="{% url 'foody:meal_list' %}" class="nav-item nav-link">Menu</a>
                    </div>
                    <a href="{% url 'foody:reserve_table' %}" class="btn btn-primary py-2 px-4">Reserve Table</a>
                </div>
            </nav>
        </div>
        <!-- Navbar & Hero End -->

        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                        {{ message | safe }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        {% block content %}
        {% endblock content %}

        <!-- Footer Start -->
        <div class="container-fluid bg-custom text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col">
                        <h4 class="ff-secondary text-h fw-normal mb-4">Foody</h4>
                        <a class="btn btn-link" href="{% url 'foody:about_us' %}">About Us</a>
                        <a class="btn btn-link" href="{% url 'foody:meal_list' %}">Our Menu</a>
                        <a class="btn btn-link" href="{% url 'foody:reserve_table' %}">Reservation</a>
                    </div>
                    <div class="col text-align-center">
                        <h1 class="text-h m-0"><i class="fa fa-hamburger me-3"></i>Foody</h1>
                    </div>
                    <div class="col text-aling-right">
                        <h4 class="ff-secondary text-h fw-normal mb-4">Contact</h4>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, Dublin, IE</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>Distributed
                            By <a class="border-bottom" href="https://themewagon.com" target="_blank">ThemeWagon</a>
                        </div>
                        <div class="col-md-6 text-end">
                            <div class="social-icons">
                                <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-outline-light btn-social" href=""><i
                                        class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                                <a class="btn btn-outline-light btn-social" href=""><i
                                        class="fab fa-linkedin-in"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript dismiss alert -->
    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 2500);
    </script>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="py-5 bg-custom hero-header mb-5">
    <div class="container text-center my-5 pt-5">
        <h1 class="display-3 text-white mb-3 animated slideInDown">{{meal_detail.name}}</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-center text-uppercase">
                <li class="breadcrumb-item"><a href="{% url 'foody:meal_list' %}">Back to Menu</a></li>
            </ol>
        </nav>
    </div>
</div>
<div class="container">
    <div class="py-5 meal-detail-col">
        <img class="img-fluid rounded-img-detail meal-img wow fadeInUp" src="{{meal_detail.image.url}}">
        <div class="details-right wow fadeInUp">
            <h5><i class="fas fa-shopping-basket icon-detail"></i> Ingredients: {{meal_detail.description}}</h5>
            <br>
            <h5><i class="fas fa-utensils icon-detail"></i> Serves: {{meal_detail.people}}</h5>
            <br>
            <h5><i class="fas fa-clock icon-detail"></i> Preparation time: {{meal_detail.preparation_time}} minutes</h5>
            <br>
            <h5><i class="fas fa-coins icon-detail"></i> Price: {{meal_detail.price}}€</h5>
        </div>
    </div>
</div>

{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block content %}

<!-- HERO Start -->
<div class="py-5 bg-dark hero-header mb-5">
    <div class="container my-5 py-5">
        <div class="row align-items-center g-5">
            <div class="col-lg-6 text-center text-lg-start">
                <h1 class="display-3 text-white animated slideInLeft">{{hero.title|safe}}</h1>
                <p class="text-white animated slideInLeft mb-4 pb-2">{{hero.content|safe}}</p>
                <a href="{% url 'foody:reserve_table' %}"
                    class="btn btn-primary py-sm-3 px-sm-5 me-3 animated slideInLeft">{{hero.cta_text}}</a>
            </div>
            <div class="col-lg-6 text-center text-lg-end overflow-hidden">
                <img class="img-fluid" src="{{hero.image.url}}">
            </div>
        </div>
    </div>
</div>
<!-- End HERO -->

<!-- Service Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-4">

            {% for card in cards %}

            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                <div class="service-item rounded pt-3">
                    <div class="p-4">
                        <span class="fa fa-3x text-h mb-4">{{card.icon|safe}}</span>
                        <h5>{{card.title}}</h5>
                        <p>{{card.content|safe}}</p>
                    </div>
                </div>
            </div>

            {% endfor %}

        </div>
    </div>
</div>
<!-- Service End -->


<!-- About Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5 align-items-center">
            <div class="col-lg-6">
                <div class="row g-3">
                    <div class="col-6 text-start">
                        <img class="img-fluid rounded w-100  wow fadeInUp"
                            src="{{about.image_left_up.url}}">
                    </div>
                    <div class="col-6 text-start">
                        <img class="img-fluid rounded w-75 wow fadeInUp"
                            src="{{about.image_right_up.url}}" style="margin-top: 25%;">
                    </div>
                    <div class="col-6 text-end">
                        <img class="img-fluid rounded w-75 wow fadeInUp"
                            src="{{about.image_left_down.url}}">
                    </div>
                    <div class="col-6 text-end">
                        <img class="img-fluid rounded w-100 wow fadeInUp"
                            src="{{about.image_right_down.url}}">
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <h5 class="section-title ff-secondary text-start text-h fw-normal">{{about.section_title}}</h5>
                <h1 class="mb-4">{{about.title}}</h1>
                <p class="mb-4">{{about.content | safe}}</p>
                <div class="row g-4 mb-4">
                    <div class="col-sm-6">
                        <div class="d-flex align-items-center border-start border-5 border-primary px-3">
                            <h1 class="flex-shrink-0 display-5 text-h mb-0" data-toggle="counter-up">{{about.number_a}}
                            </h1>
                            <div class="ps-4">
                                <p class="mb-0">{{about.title_a_small}}</p>
                                <h6 class="text-uppercase mb-0">{{about.title_a_big}}</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="d-flex align-items-center border-start border-5 border-primary px-3">
                            <h1 class="flex-shrink-0 display-5 text-h mb-0" data-toggle="counter-up">{{about.number_b}}
                            </h1>
                            <div class="ps-4">
                                <p class="mb-0">{{about.title_b_small}}</p>
                                <h6 class="text-uppercase mb-0">{{about.title_b_big}}</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About End -->

<!-- Testimonial Start -->
<div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container">
        <div class="text-center">
            <h5 class="section-title ff-secondary text-center text-h fw-normal">Testimonial</h5>
            <h1 class="mb-5">Our Clients Say!!!</h1>
        </div>
        <div class="owl-carousel testimonial-carousel">

            {% for testimonial in testimonials %}

            <div class="testimonial-item bg-transparent border rounded p-4">
                <i class="fa fa-quote-left fa-2x text-h mb-3"></i>
                <p>{{testimonial.content}}</p>
                <div class="d-flex align-items-center">
                    <img class="img-fluid flex-shrink-0 rounded-circle" src="{{testimonial.image.url}}"
                        style="width: 50px; height: 50px;">
                    <div class="ps-3">
                        <h5 class="mb-1">{{testimonial.name}}</h5>
                    </div>
                </div>
            </div>

            {% endfor %}

        </div>
    </div>
</div>
</div>
<!-- Testimonial End -->

{% endblock content %}

templates/list.html
{% extends 'base.html' %}

{% block content %}

<div class="py-5 bg-dark hero-header mb-5">
    <div class="container text-center my-5 pt-5">
        <h1 class="display-3 text-white mb-3 animated slideInDown">Check our Menu</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-center text-uppercase">
                <li class="breadcrumb-item"><a href="{% url 'foody:home' %}">Home</a></li>
                <li class="breadcrumb-item text-white active" aria-current="page">Our Menu</li>
            </ol>
        </nav>
    </div>
</div>

<!-- Menu Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h5 class="section-title ff-secondary text-center text-h fw-normal">Food Menu</h5>
            <h1 class="mb-5">Most Popular Items</h1>
        </div>
        <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.1s">
            <ul class="nav nav-pills d-inline-flex justify-content-center border-bottom mb-5">

                {% for category in categories %}

                <li class="nav-item">
                    <a class="d-flex align-items-center text-start mx-3 ms-0 pb-3" data-bs-toggle="pill"
                        id="{{category}}-tab" href="#{{category}}">
                        <div class="ps-3">
                            <h6 class="mt-n1 mb-0">{{category}}</h6>
                        </div>
                    </a>
                </li>

                {% endfor %}

            </ul>

            <div class="tab-content">

                {% for category in categories %}

                <div id="{{category}}" class="tab-pane fade show p-0 active">
                    <div class="row g-4">

                        {% for meal in meal_list %}

                        {% if meal.category == category %}

                        <div>
                            <div class="d-flex align-items-center">
                                <img class="img-fluid rounded meal-img" style="width: 80px;" src="{{meal.image.url}}">
                                <div class="w-100 d-flex flex-column text-start ps-4">
                                    <h5 class="d-flex justify-content-between border-bottom pb-2">
                                        <span><a href="{% url 'foody:meal_detail' meal.slug %}">{{meal.name}}</a></span>
                                        <span class="text-h">€ {{meal.price}}</span>
                                    </h5>
                                    <small class="fst-italic">{{meal.description}}</small>
                                </div>
                            </div>
                        </div>

                        {% endif %}

                        {% endfor %}

                    </div>
                </div>

                {% endfor %}

            </div>
        </div>
    </div>
</div>
<!-- Menu End -->

{% endblock content %}